"""Add ProjectGrade model and Contribution title field

Revision ID: 7bb78f65018e
Revises: 8585c4d060c0
Create Date: 2026-03-11 12:00:09.683990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bb78f65018e'
down_revision = '8585c4d060c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.Float(), nullable=False),
    sa.Column('letter_grade', sa.String(length=5), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('contribution_score', sa.Float(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('teamwork_score', sa.Float(), nullable=True),
    sa.Column('timeliness_score', sa.Float(), nullable=True),
    sa.Column('is_final', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('graded_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['graded_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'student_id', name='unique_project_student_grade')
    )
    with op.batch_alter_table('contributions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contributions', schema=None) as batch_op:
        batch_op.drop_column('title')

    op.drop_table('project_grades')
    # ### end Alembic commands ###
